# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
